#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config bottom_padding       32

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Emacs desktop='^2' state=tiled
bspc rule -a Zotero desktop='^4'

# problems with java gui
wmname LG3D

# IBUS
# ibus-daemon -drxR

# polybar example &
compton &
rescuetime

# Xp-Pen 
